### ISSUE TITLE
Included schemas not seeing all types

### ISSUE THREAD

**Issue by nicklauslittle-gov** [xs-parser/xs-parser#17]
When an included schema references a type in the current schema the following error is generated:

```
xs.parser.SchemaParseException: Failed to find type definition: {http://my/namespace}MyType
	at xs.parser.Schema.lambda$static$40(Schema.java:555)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at xs.parser.Schema.lambda$static$41(Schema.java:555)
	at xs.parser.Schema.lambda$find$50(Schema.java:571)
	at xs.parser.internal.Deferred$1.get(Deferred.java:33)
	at xs.parser.Element.type(Element.java:325)
```

For example, in `a.xsd`:

```xsd
<xs:include schemaLocation="b.xsd"/>
<xs:simpleType name="MyType" ...
```

and in `b.xsd`:

```xsd
<xs:element name="field" type="MyType"/>
```

This occurs in version 1.0.

**Comment by tbateson** [comment]
I believe this is working as intended. It doesn't seem to me that in your example `b.xsd` is a valid schema. I think the correct way to implement what you're trying to do using either `xs:redefine` or `xs:override`.

```xml
<xs:override schemaLocation="b.xsd">
  <xs:simpleType name="MyType" ... />
</xs:override>
```

**Comment by nicklauslittle-gov** [comment]
Here is a complete example showing the failure:

```java
import java.io.FileInputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

import org.xml.sax.InputSource;

import xs.parser.ComplexType;
import xs.parser.Element;
import xs.parser.ModelGroup;
import xs.parser.Particle;
import xs.parser.Schema;
import xs.parser.TypeDefinition;
import xs.parser.internal.NodeHelper;

public class Main {

	private static final List<String> aSchemaText = Arrays.asList("<?xml version=\"1.0\"?>",
			"<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" targetNamespace=\"a\">",
			"",
			"  <xs:include schemaLocation=\"b.xsd\" />",
			"",
			"  <xs:complexType name=\"AType\">",
			"    <xs:sequence>",
			"      <xs:element name=\"AElement\" type=\"xs:string\" />",
			"    </xs:sequence>",
			"  </xs:complexType>",
			"",
			"</xs:schema>");

	private static final List<String> bSchemaText = Arrays.asList("<?xml version=\"1.0\"?>",
			"<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" targetNamespace=\"a\" xmlns:a=\"a\">",
			"",
			"  <xs:complexType name=\"BType\">",
			"    <xs:sequence>",
			"      <xs:element name=\"BElement\" type=\"a:AType\" />",
			"    </xs:sequence>",
			"  </xs:complexType>",
			"",
			"</xs:schema>");

	public static void main(String[] args) {
		try {
			Files.write(Paths.get("a.xsd"), aSchemaText, StandardCharsets.UTF_8);
			Files.write(Paths.get("b.xsd"), bSchemaText, StandardCharsets.UTF_8);

			final Schema schema;

			try (final FileInputStream stream = new FileInputStream("a.xsd")) {
				final InputSource source = new InputSource(stream);
				source.setSystemId(Paths.get("a.xsd").toUri().toString());
				schema = new Schema(NodeHelper.newDocumentBuilder().parse(source));
			}

			for (TypeDefinition type : schema.typeDefinitions()) {
				if (type instanceof ComplexType) {
					final ComplexType complexType = (ComplexType) type;
					final ModelGroup modelGroup = (ModelGroup) complexType.contentType().particle().term();

					for (final Particle<?> particle : modelGroup.particles()) {
						System.out.println(complexType.name() + " - " + ((Element) particle.term()).name() + ":" + ((Element) particle.term()).type().name());
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}

}
```
